version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - type: bind
        source: ./rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
      - type: bind
        source: ./rabbitmq-defs.json
        target: /etc/rabbitmq/rabbitmq-defs.json
    ports:
      - 15672:15672
      - 5672:5672
  orders-app:
    build: .
    image: raulourenco/orders-app
    container_name: orders
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - rabbitmq